config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  get '/recipes/:recipe_id/shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'
  devise_scope :user do
    authenticated :user do
      root :to => 'recipes#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'recipes#public_recipes', as: :unauthenticated_root
    end
  end
  
  resources :users, only: [] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :new, :create, :show, :destroy]
  end

  resources :recipes, only: [:index, :new, :create, :show, :update, :destroy] do
    resources :recipe_foods
  end

  resources :foods, only: [:index, :new, :create, :destroy]
  root 'render#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :public_recipes, Recipe
    can :read, Recipe, public: true
    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :measurement_unit, presence: true, length: { maximum: 20 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 250 }
  validates :description, length: { maximum: 2000 }
  validates :preparation_time, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :foods, dependent: :delete_all
  has_many :recipes, dependent: :delete_all

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.all.order(:name)
  end

  def show
    set_food
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to @food, notice: 'Food was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    set_food
    @food.destroy!
    redirect_to foods_path, notice: 'Successfully destroyed foodlist.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def set_food
    @food = Food.find(params[:id])
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def show; end

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]
    if @recipe_food.save
      flash[:success] = 'recipe_food created successfully!'
      redirect_to recipe_url(params[:recipe_id])
    else
      flash.now[:error] = 'Error: recipe_food could not be created!'
      render :new, locals: { recipe_food: @recipe_food }
    end
  end

  def destroy
    set_recipe_food
    @recipe_food.destroy
    redirect_to recipe_url(params[:recipe_id])
  end

  def edit
    set_recipe_food
  end

  def update
    set_recipe_food
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_url(params[:recipe_id])
    else
      render 'edit'
    end
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = current_user.recipes.order(id: :asc)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:success] = 'recipe created successfully!'
      redirect_to recipes_url
    else
      flash.now[:error] = 'Error: recipe could not be created!'
      render :new, locals: { recipe: @recipe }
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!
    flash[:success] = 'Recipe deleted successfully!'
    redirect_to recipes_url
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.public
      @recipe.update!(public: false)
      flash[:notice] = 'Recipe status changed to private'
    else
      @recipe.update!(public: true)
      flash[:notice] = 'Recipe status changed to public'
    end
    redirect_to recipe_path
  end

  def public_recipes
    @recipes = Recipe.includes([:user, { recipe_foods: [:food] }]).where(public: true).order(id: :asc)
    @recipes_with_food_info = @recipes.map do |recipe|
      {
        recipe:,
        total_food_items: recipe.recipe_foods.size,
        total_price: recipe.recipe_foods.sum { |recipe_food| recipe_food.food.price * recipe_food.quantity }
      }
    end
  end

  def shopping_list
    @recipe = Recipe.includes([recipe_foods: [:food]]).find(params[:recipe_id])
    @recipe_data = {
      total_food_items: @recipe.recipe_foods.size,
      total_price: @recipe.recipe_foods.sum { |recipe_food| recipe_food.food.price * recipe_food.quantity }
    }
    # @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/render_helper.rb
module RenderHelper
end

app/views/foods/index.html.erb
<h1>My food ingredients 🧅🧀🥕🫚</h1>

<% if (can? :create, Recipe) %>
  <%= link_to 'Add food', new_food_path, class:'btn btn-primary' %>
<% end %>

<ul class= 'my-4 container'>
  <li class="row align-items-center bg-body-tertiary">
    <div class='col'>
      <p>Name</p>
    </div>
    <div class='col'>
      <p>Measurement unit</p>
    </div>
    <div class='col'>
      <p>Price</p>
    </div>
    <div class='col'>
      <p>Action</p>
    </div>
  </li>
  <% @foods.each_with_index do |food, i| %>
      <li class="row align-items-center <%= i.even? ? '' : 'bg-body-secondary' %>">
        <div class='col'>
        <%= link_to user_food_path(current_user, food), class:'text-decoration-none' do %>
          <h5><%= food.name %></h5>
        <% end %>
        </div>
        <div class='col'>
          <p><%= food.measurement_unit %></p>
        </div>
        <div class='col'>
          <p><%= food.price %></p>
        </div>
        <div class='col'>
          <% if can? :destroy, food %>
            <%= form_with model: food, url: food_path(food), method: :delete do |f| %>
              <%= f.submit "Remove", class: 'btn btn-danger' %>
            <% end %>
          <% end %>
        </div>
      </li>
  <% end %>
</ul>

app/views/foods/new.html.erb
<h1>Create a new food ingredient 🧅</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= form_with(model: [current_user, Food.new], local: true) do |f| %>
  <%= f.label :name, class: "form-label" %><br>
  <%= f.text_field :name, class: "form-control", required: true %><br>

  <%= f.label :measurement_unit, class: "form-label" %><br>
  <%= f.text_field :measurement_unit, class: "form-control", required: true %><br>

  <%= f.label :quantity, class: "form-label" %><br>
  <%= f.number_field :quantity, class: "form-control" %><br>

  <%= f.label :price, class: "form-label" %><br>
  <%= f.number_field :price, class: "form-control", required: true %><br>

  <%= f.submit "Create Food", class: "btn btn-primary mt-2" %>
<% end %>

app/views/foods/show.html.erb
<p class="mb-2"><strong>Name:</strong> <%= @food.name %></p>
<p class="mb-2"><strong>Measurement Unit:</strong> <%= @food.measurement_unit %></p>
<p class="mb-2"><strong>Quantity:</strong> <%= @food.quantity %> <%= @food.measurement_unit %></p>
<p class="mb-2"><strong>Price:</strong> $<%= @food.price %></p>

<%= button_to "Delete", food_path(@food.id), method: :delete, class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body class='container'>
    <header>

      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <%= link_to "RoRecipes" , user_signed_in? ? authenticated_root_path : unauthenticated_root_path, class: 'navbar-brand'%>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Public recipes", public_recipes_path, class:'nav-link' %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "My recipes", recipes_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "My foods", foods_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "New recipe", new_recipe_path, class:'nav-link' %>
                </li>
              <% end %>
              <% if current_user %>
                  <li class="nav-item">
                    <%= link_to "Profile", edit_user_registration_path, class:'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, 'data-turbo-method': :delete, class:'nav-link'%>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "Log in", new_user_session_path, class:'nav-link' %>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<h1>Edit Ingredient<br><br>🧄🥕🧀🫚</h1>

<%= form_with(url: recipe_recipe_food_path, model: @recipe_food) do |form| %>
    <div class='row align-items-end'>
        <div class="col">
            <%= form.label :quantity, class: "form-label" %>
            <%= form.number_field :quantity, class: "form-control", min: 1, required: true %>
        </div>
        <div class="col">
            <%= form.label :food_id, class: "form-label" %>
            <%= form.collection_select :food_id, current_user.foods, :id, :name, { include_blank: false }, class: "form-control" %>
        </div>
        <div class="col-2">
            <%= form.submit "Save changes", class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

<%= link_to "Add new food", new_food_path, class: "btn btn-secondary mt-4" %>

app/views/recipe_foods/new.html.erb
<h1>Add New Ingredient 🫚</h1>

<%= form_with(url: recipe_recipe_foods_path, model: @recipe_food, class: "form container") do |form| %>
    <div class='row align-items-end'>
        <div class="col">
            <%= form.label :quantity, class: "form-label" %>
            <%= form.number_field :quantity, class: "form-control", min: 1, value: 1, required: true %>
        </div>
        <div class="col">
            <%= form.label :food_id, class: "form-label" %>
            <%= form.collection_select :food_id, current_user.foods, :id, :name, { include_blank: false }, class: "form-control" %>
        </div>
        <div class="col-2">
            <%= form.submit "Add new ingredient", class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

<%= link_to "Add new food", new_food_path, class: 'btn btn-secondary mt-4' %>

app/views/recipes/index.html.erb
<h1>My Recipes 🍗🍔🥙🍟</h1>

<% if (can? :create, Recipe) %>
  <%= link_to 'Add Recipe', new_recipe_path, class:'btn btn-primary' %>
<% end %>

<ul class='list-group my-4'>
  <% @recipes.each do |recipe| %>
    <li class="list-group-item list-group-item-action container">
      <div class='row align-items-center'>
        <div class='col'>
          <%= link_to recipe_path(recipe), class:'text-decoration-none' do %>
            <h2><%= recipe.name %></h2>
          <% end %>
          <% if can? :destroy, recipe %>
            <%= form_with model: recipe, url: recipe_path(recipe), method: :delete do |f| %>
              <%= f.submit "Remove", class: 'btn btn-danger'  %>
            <% end %>
          <% end %>
        </div>
        <div class='col'>
        <p><%= truncate(recipe.description, length: 100, omission: '...') %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>Create a new Recipe 🥙</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= form_with model: [@recipe], data: { turbo: false }, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", required: true %><br>
    
    <%= f.label :preparation_time %><br>
    <%= f.number_field :preparation_time, class: "form-control", required: true, step: 0.1 %><br>
    
    <%= f.label :cooking_time %><br>
    <%= f.number_field :cooking_time, class: "form-control", required: true, step: 0.1 %><br>
    
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %><br>
    
    <%= f.label :public %><br>
    <%= f.check_box :public, class: "form-check-input" %><br>

    <%= f.submit "Create Recipe", class: "btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/recipes/public_recipes.html.erb
<h1>Public Recipes <br><br>🥙🍔🍟😋</h1>

<ul class="list-group">
  <% @recipes_with_food_info.each do |data| %>
    <li class="list-group-item list-group-item-action container">
      <div class='row align-items-center'>
        <div class='col'>
          <%= link_to recipe_path(data[:recipe]), class:'text-decoration-none' do %>
            <h2><%= data[:recipe].name %></h2>
            <p>by <%= data[:recipe].user.name %></p>
          <% end %>
        </div>
        <div class='col container'>
          <div class='row'>
            <div class='col'>
              <p>Total food items: <%= data[:total_food_items] %></p>
              <p>Total price: <%= data[:total_price] %></p>
            </div>
            <div class='col d-flex justify-content-end align-items-center'>
              <% if can? :destroy, data[:recipe] %>
                <%= form_with model: @recipes, url: recipe_path(data[:recipe]), method: :delete do |f| %>
                  <%= f.submit "Remove", class: 'btn btn-danger' %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/recipes/shopping_list.html.erb
<h1>Shopping list</h1>
<h3>Recipe: <%= @recipe.name %></h3>
<div id='recipe-info' class='d-flex justify-content-between align-items-center'>
  <p>Amount of food items to buy: <%= @recipe_data[:total_food_items] %> </p>
  <p>Total value of food needed: $<%= @recipe_data[:total_price] %></p>
</div>

<table class="table">
  <thead class="border-b">
    <tr>
      <th class='col'>Food</th>
      <th class='col'>Quantity</th>
      <th class='col'>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <th class='food-name' scope='row' ><%= recipe_food.food.name %></th>
        <td class='food-quantity' ><%= recipe_food.food.quantity %> <%= recipe_food.food.measurement_unit %></td>
        <td class='food-price' >$<%= (recipe_food.food.price*recipe_food.food.quantity).round(2) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/show.html.erb
<div>
  <div class='d-flex justify-content-between align-items-center'>
    <h1><%= @recipe.name %></h1>
    <% if current_user == @recipe.user %>
      <%= button_to recipe_path(@recipe.id), :method => :patch, class:'btn btn-secondary' do %>
        <% if @recipe.public %>
          make private
        <% else %>
          make public
        <% end %>
      <% end %>
    <% end %>
  </div>
  <p>Preparation time: <%= @recipe.preparation_time %> <%= "hour".pluralize(@recipe.preparation_time) %></p>
  <p>Cooking time: <%= @recipe.cooking_time %> <%= "hour".pluralize(@recipe.cooking_time) %></p>
  <p><%= @recipe.description %></p>
</div>


<% if current_user == @recipe.user %>
  <div class='d-flex justify-content-between align-items-center'>
    <%= link_to "Generate shopping list", shopping_list_path(@recipe.id), class:'btn btn-secondary' %>
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), class:'btn btn-primary' %>
  </div>
<% end %>

<table class="table">
  <thead class="border-b">
    <tr>
      <th class='col'>Food</th>
      <th class='col'>Quantity</th>
      <th class='col'>Value</th>
      <% if can? :destroy, @recipe %>
        <th class='col'>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <tr class='recipe_food'>
        <th scope='row' ><%= recipe_food.food.name %></th>
        <td><%= recipe_food.quantity %></td>
        <td><%= recipe_food.food.price * recipe_food.quantity %></td>
        <% if can? :destroy, @recipe %>
          <td>
            <div  class='d-flex align-items-center'>
            <%= button_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class:'btn btn-danger' %>
            <%= link_to "Edit", edit_recipe_recipe_food_path(@recipe, recipe_food), class:'btn btn-secondary' %>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>